<?php

namespace autoagisBundle\Repository;

/**
 * commerciauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commerciauxRepository extends \Doctrine\ORM\EntityRepository
{
}
