<?php

namespace autoagisBundle\Repository;

/**
 * HabitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabitationRepository extends \Doctrine\ORM\EntityRepository
{
}
